#! /bin/bash

set -ex

if ! [ -d chroot ]; then
    mkdir chroot
    debootstrap --arch amd64 testing chroot http://http.debian.net/debian/
fi

if ! [ -e chroot/usr/sbin/grub-mkconfig ]; then
    chroot chroot <<EOF
set -ex
apt-get update
yes |apt-get install -y grub2 grub-efi-amd64-bin grub-pc-bin gdisk dosfstools
EOF
fi

rsync -av --delete assets chroot
